/** Login-outcome detection on LinkedIn sign-in pages (served at their real URLs). */
import assert from 'node:assert/strict'
import { after, describe, it } from 'node:test'
import { classifyLogin, type LoginSnapshot, readLoginState } from '../src/linkedin/playwright/login.ts'
import { closeBrowser, closePage, fixture, linkedInPage } from './helpers/linkedin-browser.ts'

after(closeBrowser)

async function stateAt(path: string, html: string) {
  const page = await linkedInPage(() => html)
  try {
    await page.goto(`https://www.linkedin.com${path}`)
    return await readLoginState(page)
  } finally {
    await closePage(page)
  }
}

const login = (passwordError = '', usernameError = '') =>
  fixture('login.html', {
    USERNAME: '',
    USERNAME_ERROR: usernameError,
    USERNAME_ERROR_CLASS: usernameError ? '' : 'hidden__imp',
    PASSWORD_ERROR: passwordError,
    PASSWORD_ERROR_CLASS: passwordError ? '' : 'hidden__imp',
  })

describe('login outcome detection', () => {
  it('feed → logged in', async () => {
    const r = await stateAt('/feed/', fixture('feed.html'))
    assert.equal(r.state, 'logged_in')
    assert.equal(r.snapshot?.loggedIn, true)
  })

  it('feed posts about restrictions or app approvals do not change a signed-in feed', async () => {
    const post = (text: string) => fixture('feed.html').replace('<p>Hello world</p>', `<p>${text}</p>`)
    for (const text of [
      'Has LinkedIn restricted your account? Here are 5 things to do.',
      'My account has been restricted for a week, ugh.',
      'New security feature: open your LinkedIn app and tap Yes to approve the sign-in.',
    ]) {
      const r = await stateAt('/feed/', post(text))
      assert.equal(r.state, 'logged_in', text)
    }
    // Even where LinkedIn's navigation can't be recognised, a post is not a challenge page.
    const noNav = post('Has LinkedIn restricted your account? Open your LinkedIn app and tap Yes!').replace(/<header[\s\S]*?<\/header>/, '')
    const r = await stateAt('/feed/', noNav)
    assert.equal(r.snapshot?.restricted, false)
    assert.equal(r.snapshot?.appApproval, false)
    assert.equal(r.state, 'logged_in')
  })

  it('the plain sign-in form', async () => {
    assert.equal((await stateAt('/login', login())).state, 'login_form')
  })

  it('wrong password / unknown email', async () => {
    assert.equal((await stateAt('/checkpoint/lg/login-submit', login('Wrong email or password. Try again or create an account.'))).state, 'wrong_credentials')
    assert.equal((await stateAt('/checkpoint/lg/login-submit', login("That's not the right password. Try again or reset your password."))).state, 'wrong_credentials')
    assert.equal(
      (await stateAt('/checkpoint/lg/login-submit', login('', 'Couldn’t find a LinkedIn account associated with this email. Please try again.'))).state,
      'wrong_credentials',
    )
    const other = await stateAt('/checkpoint/lg/login-submit', login('Please enter a password.'))
    assert.equal(other.state, 'login_error')
  })

  it('email / SMS PIN challenge', async () => {
    const r = await stateAt('/checkpoint/challenge/AgH123', fixture('checkpoint-pin.html', { ERROR: '', ERROR_CLASS: 'hidden__imp' }))
    assert.equal(r.state, 'pin')
    assert.equal(r.snapshot?.description, 'The verification code has been sent to s***@example.com')
    assert.equal(r.snapshot?.formError, '')
    const wrong = await stateAt('/checkpoint/challenge/verify', fixture('checkpoint-pin.html', { ERROR: 'The verification code you entered isn’t valid.', ERROR_CLASS: '' }))
    assert.equal(wrong.state, 'pin')
    assert.match(wrong.snapshot?.formError ?? '', /isn’t valid/)
  })

  it('authenticator-app code (two-step verification)', async () => {
    const html = `<!doctype html><html><body><main><h1>Two-step verification</h1><p>Enter the verification code generated by your authenticator app.</p>
      <form method="post" action="/checkpoint/challenge/verify"><input id="input__phone_verification_pin" name="pin" type="text" autocomplete="one-time-code">
      <button id="two-step-submit-button" type="submit">Submit</button></form></main></body></html>`
    assert.equal((await stateAt('/checkpoint/challenge/AgTwoStep', html)).state, 'pin')
  })

  it('approve in the LinkedIn app', async () => {
    assert.equal((await stateAt('/checkpoint/challenge/AgApp', fixture('checkpoint-app.html'))).state, 'app_approval')
  })

  it('captcha security check', async () => {
    assert.equal((await stateAt('/checkpoint/challenge/AgCaptcha', fixture('checkpoint-captcha.html'))).state, 'captcha')
  })

  it('post-login interstitials, restrictions and unknown checkpoints', async () => {
    assert.equal((await stateAt('/check/add-phone', '<html><body><main><h1>Add a phone number</h1></main></body></html>')).state, 'interstitial')
    assert.equal(
      (await stateAt('/checkpoint/challenge/AgR', '<html><body><main><h1>Your account has been restricted</h1><p>We’ve restricted your account temporarily.</p></main></body></html>')).state,
      'restricted',
    )
    assert.equal((await stateAt('/checkpoint/challenge/AgX', '<html><body><main><h1>One more step</h1></main></body></html>')).state, 'challenge')
    assert.equal((await stateAt('/feed/', '<html><body><script>/* redirecting */</script></body></html>')).state, 'unknown', 'a blank /feed/ document is not a feed')
  })

  it('classifies snapshots without a page', () => {
    const base: LoginSnapshot = {
      url: 'https://www.linkedin.com/feed/',
      loggedIn: true,
      hasMain: true,
      loginForm: false,
      pinInput: false,
      appApproval: false,
      captcha: false,
      restricted: false,
      usernameError: '',
      passwordError: '',
      formError: '',
      heading: '',
      description: '',
    }
    assert.equal(classifyLogin(base), 'logged_in')
    assert.equal(classifyLogin({ ...base, url: 'https://www.linkedin.com/mynetwork/' }), 'logged_in')
    assert.equal(classifyLogin({ ...base, url: 'https://www.linkedin.com/checkpoint/challenge/x', loggedIn: false, pinInput: true }), 'pin')
    assert.equal(classifyLogin({ ...base, url: 'not a url' }), 'unknown')
  })
})
